name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build & push Docker image
      uses: docker/build-push-action@v1
      with:
        repository: unipeer/chainlink-upi-adapter/upi-adapter
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_with_ref: true
        push: ${{ startsWith(github.ref, 'refs/tags/') }}
